### ISSUE TITLE
modular system for source code

### ISSUE THREAD

**Issue by mterber** [boschresearch/blech#10]
**Is your feature request related to a problem? Please describe.**
Today, the entire source code of a Blech program resides in a single *.blc file. This
- reduces the clarity of the code (even for small projects)
- provides only a single name space for all functions, activities, etc.
- makes it hard to separate concerns

**Describe the solution you'd like**
I would like to be able to separate my Blech code into different source files and to import / include them if required. Example:

```
// @file: spi.blc - Everything related to SPI communication.
module spi
activity rxTxBytes(...)
...
end
```

```
// @file: rf.blc - Everything related to RF communication.
import spi
...
run spi.rxTxBytes(...)
...
```

**Comment by schorg** [comment]
Module system will be released in Version 0.7.0
