### ISSUE TITLE
Syntax error for "next" as identifier

### ISSUE THREAD

**Issue by mterber** [boschresearch/blech#14]
**Describe the bug**
When I use the word "next" as an identifier for a variable I receive a syntax error. If I rename the variable, e.g. to "next1", then the error is gone.

> syntax error 'next'.parsing
test.blc(9, 1): start of chunk.
test.blc(10, 9): unexpected token.

**To Reproduce**
```
function cbuf_push () (head: nat16)
    var next: nat16 = head + 1
end
```

**Expected behaviour**
I would expect no syntax error because according to https://github.com/boschresearch/blech-doc/blob/master/documentation/blech-user-manual/lexical.adoc "next" does not seem to be a keyword (or special in any sense).

**Screenshots**
![syntax_error](https://user-images.githubusercontent.com/13783234/77818606-ffc91500-70d3-11ea-8a03-582001a04051.png)

**Comment by schorg** [comment]
'next' is a reserved keyword. It's dual to 'prev' and will become necessary for parallel blech.

**Comment by mterber** [comment]
Okay, thanks for the clarification.
