### ISSUE TITLE
generated h file always contains print prototype

### ISSUE THREAD

**Issue by FriedrichGretz** [boschresearch/blech#57]
**Describe the bug**
Run `blechc` WITHOUT `--trace` argument. The generated C code does not have a printState function accordingly. Yet the corresponding header unnecessarily declares a printState prototype.

**Comment by schorg** [comment]
Fixed it with commit https://github.com/boschresearch/blech/commit/669c2cc2df2fb15c66db9930a50f5e8eeb47efe4
