### ISSUE TITLE
Blech syntax highlighting in GitHub 

### ISSUE THREAD

**Issue by frameworklabs** [boschresearch/blech#60]
**Is your feature request related to a problem? Please describe.**
When looking at Blech code (.blc - soon  also .blh) on GitHub keywords and other lexical entities (comments etc) are not highlighted / colored. This makes reading Blech code less pleasant.

**Describe the solution you'd like**
Add syntax coloring/highlighting for Blech files on GitHub (and maybe other Source Repos?)
The coloring behavior would be equal to what the Blech VS Code Plugin does.

**Comment by schorg** [comment]
Github uses [Linguist](https://github.com/github/linguist) for syntax highlighting.

There is an [article on Medium about it](https://medium.com/@bolajiayodeji/introducing-github-linguist-8f09273ddea1).

From the contribution guide:
> We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in at least 200 unique :user/:repo repositories before supporting them in Linguist.
